services:
  - type: web
    name: jamcchurch-backend
    env: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://jamcchurch.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: jamctagoloan_backend
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: your-db-password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
