services:
  - type: web
    name: jamcchurch-backend
    env: php
    buildCommand: |
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader
      cp .env.example .env
      php artisan config:clear
      php artisan key:generate
      php artisan migrate --force
      npm install
      npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://jamcchurch.com
      - key: APP_KEY
        generateValue: true

      # === ✅ FIXED Database Variables from Railway ===
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: hopper.proxy.rlwy.net
      - key: DB_PORT
        value: 39230
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: DnAWPPQDqHaTWbpVHPtChWucrMvOLDeT

      # === Laravel Specific Settings ===
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
